# Generated by Django 4.2 on 2024-04-25 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_alter_itemtime_item_alter_order_items'),
        ('stock', '0007_itemorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemOrder',
        ),
    ]
