# Generated by Django 4.2 on 2024-04-30 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_itemorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemorder',
            name='code',
            field=models.CharField(max_length=15, verbose_name='Código'),
        ),
    ]
