services:
  db:
    container_name: mariadb_refriall
    image: mariadb:11.8
    ports:
      - "3306:3306"
    volumes:
      - mariadb_refriall:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
    restart: always
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  pma:
    depends_on:
      db:
        condition: service_healthy
    container_name: phpmyadmin_refriall
    image: phpmyadmin:5.2
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    restart: always
  
  django_backend:
    depends_on:
      db:
        condition: service_healthy
    build: .
    container_name: django_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    develop:
      watch:
        # Sync the working directory for code changes ignoring 
        # the virtual environment
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        # Rebuild the image if new dependencies or settings are written
        # to the pyproject.toml
        - action: rebuild
          path: ./pyproject.toml

volumes:
  mariadb_refriall: