services:
  db:
    container_name: mariadb_refriall
    image: mariadb:11.8
    ports:
      - "3306:3306"
    volumes:
      - mariadb_refriall:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
    restart: always
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  pma:
    depends_on:
      db:
        condition: service_healthy
    container_name: phpmyadmin_refriall
    image: phpmyadmin:5.2
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    restart: always
  
  refriall_frontend:
    container_name: vuejs_refriall
    depends_on:
      db:
        condition: service_healthy
    build:
      context: ./refriall_frontend
      dockerfile: Dockerfile
    volumes:
      - refriall_fronted_dist:/app/dist
    command: echo "Vue build completed"
    restart: "no"
  
  django_backend:
    depends_on:
      # django needs to collect static files
      # from vuejs building
      refriall_frontend:
        condition: service_completed_successfully
    build: .
    container_name: django_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - refriall_fronted_dist:/app/dist
    restart: always

volumes:
  mariadb_refriall:
  refriall_fronted_dist:
