# Generated by Django 4.2 on 2024-01-30 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_order_customer_dependency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='folio',
            field=models.CharField(max_length=10, unique=True, verbose_name='No. folio'),
        ),
    ]
