# Generated by Django 4.2 on 2024-01-30 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_order_matched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='matched',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
