# Generated by Django 4.2 on 2024-01-30 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0005_alter_customerdependency_customer'),
        ('finance', '0006_alter_order_matched'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=10, unique=True, verbose_name='No. folio')),
                ('provider_signature_date', models.DateField(verbose_name='Firma del proveedor')),
                ('customer_signature_date', models.DateField(verbose_name='Firma del cliente')),
                ('matched', models.BooleanField(default=False, editable=False)),
                ('check_number', models.CharField(blank=True, max_length=35, null=True, verbose_name='Nro. de Cheque')),
                ('charge_aprove', models.CharField(blank=True, max_length=35, null=True, verbose_name='Cargo aprueba')),
                ('charge_check', models.CharField(blank=True, max_length=35, null=True, verbose_name='Cargo revisa')),
                ('customer_charge', models.CharField(blank=True, max_length=25, null=True, verbose_name='Cargo')),
                ('customer_name', models.CharField(blank=True, max_length=25, null=True, verbose_name='Nombre')),
                ('customer_personal_id', models.CharField(blank=True, max_length=11, null=True, verbose_name='No. CI')),
                ('checked_by', models.CharField(blank=True, max_length=35, null=True, verbose_name='Revisado por')),
                ('aproved_by', models.CharField(blank=True, max_length=35, null=True, verbose_name='Aprobado por')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hr.customer', verbose_name='Cliente')),
                ('customer_dependency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hr.customerdependency', verbose_name='Dependencia')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Prestador')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['provider_signature_date'],
            },
        ),
    ]
