# Generated by Django 4.2 on 2024-03-31 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_alter_order_customer_signature_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='customer_dependency',
        ),
    ]
