# Generated by Django 4.2 on 2024-04-20 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_alter_itemtime_item_alter_order_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemtime',
            old_name='item',
            new_name='item_order',
        ),
    ]
