# Generated by Django 4.2 on 2024-04-25 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_alter_itemtime_item_alter_order_items'),
        ('finance', '0018_alter_bill_customer_signature_date'),
    ]

    operations = [
    ]
