# Generated by Django 4.2 on 2024-04-25 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_itemorder'),
        ('finance', '0020_alter_order_customer_signature_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtime',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stock.item', verbose_name='Artículo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(blank=True, editable=False, through='finance.ItemTime', to='stock.item', verbose_name='Artículo o Servicio'),
        ),
    ]
