# Generated by Django 4.2 on 2024-04-30 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0024_alter_itemtimeorder_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='kit_serial',
            field=models.CharField(max_length=30, verbose_name='No. de serie o Inv.'),
        ),
    ]
