# Generated by Django 4.2 on 2026-03-23 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0030_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['-provider_signature_date'], 'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),
    ]
