# Generated by Django 4.2 on 2023-12-21 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='support',
            field=models.CharField(choices=[('t', 'Taller'), ('i', 'In Situ')], default='i', max_length=1),
            preserve_default=False,
        ),
    ]
