# Generated by Django 4.2 on 2024-01-30 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_order_folio'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='matched',
            field=models.BooleanField(default=False),
        ),
    ]
