# Generated by Django 4.2 on 2024-01-30 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_order_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='matched',
        ),
    ]
