# Generated by Django 4.2 on 2024-02-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_remove_order_matched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_signature_date',
            field=models.DateField(null=True, verbose_name='Firma del cliente'),
        ),
        migrations.AlterField(
            model_name='order',
            name='provider_signature_date',
            field=models.DateField(null=True, verbose_name='Firma del proveedor'),
        ),
    ]
