# Generated by Django 4.2 on 2024-04-25 19:34

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_remove_order_provider_signature_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='provider_signature_date',
            field=models.DateField(default=timezone.now().date(), verbose_name='Firma del proveedor'),
            preserve_default=False,
        ),
    ]
