# Generated by Django 4.2 on 2024-04-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_merge_20240425_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_signature_date',
            field=models.DateField(blank=True, null=True, verbose_name='Firma del cliente'),
        ),
    ]
