# Generated by Django 4.2 on 2024-04-26 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_itemorder'),
        ('finance', '0023_order_items_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtimeorder',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.itemorder', verbose_name='Artículo'),
        ),
    ]
