# Generated by Django 4.2 on 2024-09-10 01:23

from django.db import migrations, models


def currency_to_bills(apps, schema_editor):
    Bill = apps.get_model('finance', 'Bill')
    Currency = apps.get_model('finance', 'Currency')
    bills = Bill.objects.all()

    if bills.count() > 0:
        currency, _ = Currency.objects.get_or_create(name='cup')
        
        for bill in bills:
            bill.currency = currency
            bill.save()
    else:
        pass



class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0026_auto_20240905_0935'),
        ('finance', '0028_alter_currency_options_alter_currency_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='Bill',
            name='currency',
            field=models.ForeignKey(
                to='finance.Currency',
                on_delete=models.PROTECT,
                related_name='bills',
                null=True
            )
        ),
        migrations.RunPython(currency_to_bills),
        migrations.AlterField(
            model_name='Bill',
            name='currency',
            field=models.ForeignKey(
                to='finance.Currency',
                on_delete=models.PROTECT,
                related_name='bills',
                null=False
            )
        )
    ]
