# Generated by Django 4.2 on 2026-03-23 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0029_auto_20240909_2123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-provider_signature_date'], 'verbose_name': 'Orden de Servicio', 'verbose_name_plural': 'Órdenes de Servicio'},
        ),
    ]
