# Generated by Django 4.2 on 2024-01-18 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_provider_activity_provider_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='activity',
            field=models.CharField(max_length=55),
        ),
    ]
