# Generated by Django 4.2 on 2024-01-19 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_alter_provider_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('province', models.CharField(max_length=20, verbose_name='Provincia')),
                ('township', models.CharField(max_length=50, verbose_name='Municipio')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.customer')),
            ],
            options={
                'verbose_name': 'Dependencia',
                'verbose_name_plural': 'Dependencias',
                'ordering': ['name'],
            },
        ),
    ]
