# Generated by Django 4.2 on 2024-01-25 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_alter_customerdependency_customer'),
        ('finance', '0002_order_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_dependency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hr.customerdependency', verbose_name='Dependencia'),
        ),
    ]
