# Generated by Django 4.2 on 2024-04-26 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_itemorder'),
        ('finance', '0021_alter_itemtime_item_alter_order_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemTimeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times', models.FloatField(default=1, verbose_name='Cantidad')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stock.itemorder', verbose_name='Artículo')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.order')),
            ],
            options={
                'verbose_name': 'Cantidad de Artículo',
                'verbose_name_plural': 'Cantidades de Artículo',
            },
        ),
    ]
