# Generated by Django 4.2 on 2024-09-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0027_alter_currency_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'Moneda', 'verbose_name_plural': 'Monedas'},
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=4, unique=True, verbose_name='Nombre'),
        ),
    ]
