# Generated by Django 5.2 on 2026-07-29 00:57

# django
from django.db import migrations, models

# third
from decouple import config

def ensure_bills_have_providers(apps, schema_editor):
    """
    Assigns the first provider to bill that don't have any,
    creates a default one in case there's None(shouldn't happen)
    """
    Bill = apps.get_model('finance', 'Bill')
    Provider = apps.get_model('hr', 'Provider')

    first_provider = Provider.objects.first()

    if first_provider:
        Bill.objects.filter(provider__isnull=True).update(provider=first_provider)
    else:
        default_provider = Provider.objects.create(
            username='provider',
            first_name='provider',
            last_name='provider',
            tcp_code='07176',
            bank_account_header='Provider provider header',
            bank_account='0689870015131710',
            address='provider street',
            activity='proovider activity',
            license_number='888',
            password=config('provider_migration_password'),
        )
        Bill.objects.filter(provider__isnull=True).update(provider=default_provider)


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0031_alter_bill_options'),
    ]

    operations = [
        migrations.RunPython(
            code=ensure_bills_have_providers,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='bill',
            name='provider',
            field=models.ForeignKey(
                to='hr.provider',
                on_delete=models.PROTECT
            )
        )
    ]
