# Generated by Django 5.2 on 2026-07-29 01:53

from django.db import migrations, models
import django.db.models.deletion

def ensure_bills_have_customer(apps, schema_editor):
    """
    Assigns the first customer to bill that doesn't have any,
    creates a default one in case there's None.
    """
    Bill = apps.get_model('finance', 'Bill')
    Customer = apps.get_model('hr', 'Customer')

    first_customer = Customer.objects.first()

    if first_customer:
        Bill.objects.filter(customer__isnull=True).update(customer=first_customer)
    else:
        default_customer = Customer.objects.create(
            customer_type='es',
            name='default customer',
            address='customer address',
            province='province',
            township='township',
            code='888',
            client_nit='client_nit',
            bank_account_header='bank_account_header',
            bank_account='bank_account'
        )
        Bill.objects.filter(customer__isnull=True).update(customer=default_customer)


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0032_auto_20260728_2057'),
    ]

    operations = [
        migrations.RunPython(
            code=ensure_bills_have_customer,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='bill',
            name='customer',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, 
                to='hr.customer', verbose_name='Cliente'
            ),
        )
    ]
