# Generated by Django 5.2 on 2026-10-02 18:00

# django
from django.conf import settings
from django.db import migrations, models

# third
from decouple import config


def kit_to_order(apps, schema_editor):
    Kit = apps.get_model("stock", "Kit")
    Provider = apps.get_model('hr', 'Provider')
    Order = apps.get_model("finance", "Order")

    if Order.objects.exists():
        # kit block
        first_kit = Kit.objects.first()

        if first_kit:
            Order.objects.filter(kit__isnull=True).update(kit=first_kit)
        else:
            default_kit = Kit.objects.create(name = 'Equipo predefinido')
            Order.objects.filter(kit__isnull=True).update(kit=default_kit)

        # provider block
        first_provider = Provider.objects.first()
        
        if first_provider:
            Order.objects.filter(provider__isnull=True).update(provider=first_provider)
        else:
            default_provider = Provider.objects.create(
                username='provider',
                first_name='provider',
                last_name='provider',
                tcp_code='07176',
                bank_account_header='Provider provider header',
                bank_account='0689870015131710',
                address='provider street',
                activity='proovider activity',
                license_number='888',
                password=config('provider_migration_password'),
            )
            Order.objects.filter(provider__isnull=True).update(provider=default_provider)


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0033_auto_20260728_2153'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL)
    ]

    operations = [
        migrations.RunPython(code=kit_to_order, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='order',
            name='kit',
            field=models.ForeignKey(
                on_delete=models.PROTECT, 
                to='stock.Kit',
                verbose_name="Equipo"
            )
        ),
        migrations.AlterField(
            model_name='order',
            name='provider',
            field=models.ForeignKey(
                on_delete=models.PROTECT, 
                to=settings.AUTH_USER_MODEL,
                verbose_name='Prestador'
            ),
        )
    ]
