# Generated by Django 4.2 on 2024-01-18 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='activity',
            field=models.CharField(default='', max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='bank_account',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='bank_account_header',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='tcp_code',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
