# Generated by Django 4.2 on 2024-01-20 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_customerdependency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdependency',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dependencies', to='hr.customer'),
        ),
    ]
