# Generated by Django 4.2 on 2024-10-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_alter_customerdependency_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='customerdependency',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
