# Generated by Django 4.2 on 2025-09-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_alter_customer_name_alter_customerdependency_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='license_number',
            field=models.CharField(max_length=16, verbose_name='Licencia'),
        ),
    ]
