# Generated by Django 4.2 on 2025-09-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_alter_provider_license_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='bank_account',
            field=models.CharField(max_length=16),
        ),
    ]
