# Generated by Django 4.2 on 2024-10-21 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_alter_item_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemorder',
            name='measurement',
            field=models.CharField(blank=True, choices=[('u', 'Uno'), ('m', 'Mts'), ('kg', 'Kgs'), ('lts', 'Lts')], max_length=3, null=True, verbose_name='Unidad de medida'),
        ),
    ]
