# Generated by Django 4.2 on 2024-10-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_alter_itemorder_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='measurement',
            field=models.CharField(blank=True, choices=[('u', 'Uno'), ('m', 'Mts'), ('kg', 'Kg'), ('lts', 'Lts'), ('gl', 'Gl'), ('tr', 'Tr'), ('pqt', 'Pqt')], max_length=3, null=True, verbose_name='Unidad de medida'),
        ),
        migrations.AlterField(
            model_name='itemorder',
            name='measurement',
            field=models.CharField(blank=True, choices=[('u', 'Uno'), ('m', 'Mts'), ('kg', 'Kg'), ('lts', 'Lts'), ('gl', 'Gl'), ('tr', 'Tr'), ('pqt', 'Pqt')], max_length=3, null=True, verbose_name='Unidad de medida'),
        ),
    ]
